### ISSUE TITLE
Request: Change The license to BSD 3-Clause

### ISSUE THREAD

**Issue by ghost** [386bsd/386bsd#7]
386BSD has way too many Clauses, UC Berkeley Changed the License for 4.4BSD Lite2 to BSD 3-clause in 1999, So it would be nice to have 386BSD with only 3 Clauses.
ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change

**Comment by jeandrek** [comment]
That would probably require replacing all the Net/2 code with 4.4BSD Lite2 code.

**Comment by ghost** [comment]
Caldera isn't credited, I'll try forking it and replacing the code.

**Comment by autumnjolitz** [comment]
Hello all.

This repository started from the CDROM release with the original sources and licenses as-is.

Work has been into making it bootable as a historical restoration project.

We have no plans towards relicensing at the moment and near future. 

Thanks for your interest!

**Comment by ghost** [comment]
That's understandable, but a bit of a bummer

Thanks for reading!
